# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fbedd23c542c41765e8e745c828043f"
name = "ImageBoost SEO"
handle = "imageboost-seo"
application_url = "https://ringtones-far-inkjet-producer.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://ringtones-far-inkjet-producer.trycloudflare.com/auth/callback",
  "https://ringtones-far-inkjet-producer.trycloudflare.com/auth/shopify/callback",
  "https://ringtones-far-inkjet-producer.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
